#ifndef SPRITES_H
#define SPRITES_H

#include "constants.h"

#define TXT_WALL_DARK  COLOR_BLUE "##" COLOR_RESET
#define TXT_WALL_LIGHT COLOR_CYAN "##" COLOR_RESET
#define TXT_FLOOR      COLOR_WHITE ". " COLOR_RESET
#define TXT_SHADOW     COLOR_BLUE ". " COLOR_RESET

const char* SPR_PLAYER = COLOR_CYAN "@ " COLOR_RESET;
const char* SPR_GUARD  = COLOR_RED "G " COLOR_RESET;
const char* SPR_GHOST  = COLOR_MAGENTA "S " COLOR_RESET;
const char* SPR_BOSS   = COLOR_RED COLOR_BOLD "B " COLOR_RESET;

const char* SPR_SWORD  = COLOR_YELLOW "/ " COLOR_RESET;
const char* SPR_KEY    = COLOR_YELLOW "K " COLOR_RESET;
const char* SPR_COFFEE = COLOR_GREEN "C " COLOR_RESET;
const char* SPR_EXIT   = COLOR_GREEN "E " COLOR_RESET;
const char* SPR_TREE   = COLOR_GREEN "T " COLOR_RESET;
const char* SPR_ROCK   = COLOR_WHITE "R " COLOR_RESET;

#define ICON_HEART COLOR_RED "<3 " COLOR_RESET
#define ICON_SWORD COLOR_YELLOW "/ " COLOR_RESET
#define ICON_KEY   COLOR_YELLOW "K " COLOR_RESET

#endif
